version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      
volumes:
  db:
    external: false
    
  